apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: ingress-app
  annotations:
    # Force the generated Route to use "Edge" termination (TLS handled by HAProxy router)
    route.openshift.io/termination: "edge"
spec:
  ingressClassName: openshift-default
  rules:
    - host: hello-world.apps-crc.testing
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8080
