# Qserv operator CI workflow
---
name: "CI"
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  main:
    name: Run nginx-controller demo
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Stop apparmor
        run: |
          sudo /etc/init.d/apparmor stop
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.21.4'
      - name: Install and run ciux
        run: |
          ./ignite.sh
      - name: Create k8s/kind cluster
        run: |
          ktbx create -s
          ktbx install helm
      - name: Create k8s/kind cluster
        run: |
          kubectl get nodes
          kubectl get pods -n kube-system
      - name: Run test on nginx-controller
        run: |
          ./setup.sh -s
